services:
  desafio-me:
    container_name: desafio-me
    image: desafio-me
    build:
      context: .
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    stdin_open: true
    tty: true 
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - me_network
  db:
    container_name: db
    image: postgres:17.5-alpine3.22
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    networks:
      - me_network
  pgadmin-biblioteca:
    container_name: pgadmin4-biblioteca
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - 5050:80
      - 5051:443
    depends_on:
      - db
    networks:
      - me_network
networks:
  me_network:
    driver: bridge